name: ros-ci

# Controls when the action will run. Triggers the workflow on push or pull request
on:
  push:
    branches: [ humble ]
  pull_request:
    branches: [ humble ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  humble:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        ros_distribution:
          - humble
        include:
          - docker_image: ubuntu:jammy
            ros_distribution: humble
            ros_version: 2
          #   # Rolling
          # - docker_image: ubuntu:jammy
          #   ros_distribution: rolling
          #   ros_version: 2
    container:
      image: ${{ matrix.docker_image }}
    steps:
      - name: Setup directories
        run: mkdir -p ros_ws/src
      - name: checkout
        uses: actions/checkout@v3
        with:
          path: ros_ws/src
      - name: Setup ROS environment
        uses: ros-tooling/setup-ros@0.3.3
        with:
          required-ros-distributions: ${{ matrix.ros_distribution }}
      - name: Build and Test
        uses: ros-tooling/action-ros-ci@0.2.5
        with:
          package-name: dynamixel_hardware_interface
          target-ros2-distro: ${{ matrix.ros_distribution }}
          vcs-repo-file-url: "https://raw.githubusercontent.com/ROBOTIS-GIT/dynamixel_hardware_interface/main/dynamixel_hardware_interface_ci.repos"
